# Generated by Django 5.1.6 on 2025-02-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('grandfather_name', models.CharField(max_length=100)),
                ('emp_id', models.CharField(max_length=50, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('body', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='employee_images/')),
                ('region', models.CharField(max_length=100)),
                ('zone', models.CharField(max_length=100)),
                ('woreda', models.CharField(max_length=100)),
                ('kebele', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('institution_name', models.CharField(max_length=200)),
                ('field', models.CharField(max_length=100)),
                ('date_of_graduate', models.DateField()),
                ('company_names', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='employee_docs/')),
                ('licence_type', models.CharField(max_length=100)),
                ('give_date', models.DateField()),
                ('expired_date', models.DateField()),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_account', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='employees', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='employees_permissions', to='auth.permission')),
            ],
            options={
                'permissions': [],
                'default_permissions': (),
            },
        ),
    ]
